In [32]:
import pandas as pd

In [33]:
data_loc='C:/Users/DELL/Projects/ecommerce-sales-pipeline/data/Location.csv'
Location= pd.read_csv(data_loc, encoding = 'latin1',sep=";")
print(Location)
Location.info

     Postal Code             City       State   Region Country/Region
0        76106.0       Fort Worth       Texas  Central  United States
1        53711.0          Madison   Wisconsin  Central  United States
2        68025.0          Fremont    Nebraska  Central  United States
3        77095.0          Houston       Texas  Central  United States
4        75080.0       Richardson       Texas  Central  United States
..           ...              ...         ...      ...            ...
627      83301.0       Twin Falls       Idaho     West  United States
628      92672.0     San Clemente  California     West  United States
629      94568.0           Dublin  California     West  United States
630      93405.0  San Luis Obispo  California     West  United States
631      95240.0             Lodi  California     West  United States

[632 rows x 5 columns]

<bound method DataFrame.info of      Postal Code             City       State   Region Country/Region
0        76106.0       Fort Worth       Texas  Central  United States
1        53711.0          Madison   Wisconsin  Central  United States
2        68025.0          Fremont    Nebraska  Central  United States
3        77095.0          Houston       Texas  Central  United States
4        75080.0       Richardson       Texas  Central  United States
..           ...              ...         ...      ...            ...
627      83301.0       Twin Falls       Idaho     West  United States
628      92672.0     San Clemente  California     West  United States
629      94568.0           Dublin  California     West  United States
630      93405.0  San Luis Obispo  California     West  United States
631      95240.0             Lodi  California     West  United States

[632 rows x 5 columns]>

In [34]:
Location['Postal Code']=Location['Postal Code'].astype('str')

In [35]:
Location.dtypes

Postal Code       object
City              object
State             object
Region            object
Country/Region    object
dtype: object

In [36]:
data_pro='C:/Users/DELL/Projects/ecommerce-sales-pipeline/data/Products.csv'
Products= pd.read_csv(data_pro, encoding = 'latin1',sep=";")
print(Products)
Products.info

                                             Product ID    Category  \
0                                       FUR-BO-10000112   Furniture
1                                       FUR-BO-10000330   Furniture
2                                       FUR-BO-10000362   Furniture
3                                       FUR-BO-10000468   Furniture
4                                       FUR-BO-10000711   Furniture
...                                                 ...         ...
1889                                    TEC-PH-10004912  Technology
1890                                    TEC-PH-10004922  Technology
1891  TEC-PH-10004924;Technology;Phones;"SKILCRAFT T...         NaN
1892                                    TEC-PH-10004959  Technology
1893                                    TEC-PH-10004977  Technology

     Sub-Category                                  Product Name,,,,,
0       Bookcases  Bush Birmingham Collection Bookcase, Dark Cher...
1       Bookcases  Sauder Camden County Barrister Bookcase, Plank...
2       Bookcases            Sauder Inglewood Library Bookcases,,,,,
3       Bookcases       O'Sullivan 2-Shelf Heavy-Duty Bookcases,,,,,
4       Bookcases                      Hon Metal Bookcases, Gray,,,,
...           ...                                                ...
1889       Phones             Cisco SPA112 2 Port Phone Adapter,,,,,
1890       Phones        RCA Visys Integrated PBX 8-Line Router,,,,,
1891          NaN                                                NaN
1892       Phones        Classic Ivory AntiqueTelephoneZL1810,,,,,
1893       Phones                                   GE 30524EE4,,,,,

[1894 rows x 4 columns]

<bound method DataFrame.info of                                              Product ID    Category  \
0                                       FUR-BO-10000112   Furniture
1                                       FUR-BO-10000330   Furniture
2                                       FUR-BO-10000362   Furniture
3                                       FUR-BO-10000468   Furniture
4                                       FUR-BO-10000711   Furniture
...                                                 ...         ...
1889                                    TEC-PH-10004912  Technology
1890                                    TEC-PH-10004922  Technology
1891  TEC-PH-10004924;Technology;Phones;"SKILCRAFT T...         NaN
1892                                    TEC-PH-10004959  Technology
1893                                    TEC-PH-10004977  Technology

     Sub-Category                                  Product Name,,,,,
0       Bookcases  Bush Birmingham Collection Bookcase, Dark Cher...
1       Bookcases  Sauder Camden County Barrister Bookcase, Plank...
2       Bookcases            Sauder Inglewood Library Bookcases,,,,,
3       Bookcases       O'Sullivan 2-Shelf Heavy-Duty Bookcases,,,,,
4       Bookcases                      Hon Metal Bookcases, Gray,,,,
...           ...                                                ...
1889       Phones             Cisco SPA112 2 Port Phone Adapter,,,,,
1890       Phones        RCA Visys Integrated PBX 8-Line Router,,,,,
1891          NaN                                                NaN
1892       Phones        Classic Ivory AntiqueTelephoneZL1810,,,,,
1893       Phones                                   GE 30524EE4,,,,,

[1894 rows x 4 columns]>

In [37]:
Products[Products[['Category','Sub-Category','Product Name,,,,,']].isna().any(axis=1)]

,Product ID,Category,Sub-Category,"Product Name,,,,,"
26,"FUR-BO-10002916;Furniture;Bookcases;""Rush Hier...",NaN,NaN,NaN
142,"FUR-FU-10000087;Furniture;Furnishings;""Executi...",NaN,NaN,NaN
147,"FUR-FU-10000222;Furniture;Furnishings;""Seth Th...",NaN,NaN,NaN
149,"FUR-FU-10000260;Furniture;Furnishings;""6"""" Cub...",NaN,NaN,NaN
152,"FUR-FU-10000305;Furniture;Furnishings;""Tenex V...",NaN,NaN,NaN
...,...,...,...,...
1479,"OFF-SU-10004782;Office Supplies;Supplies;""Elit...",NaN,NaN,NaN
1615,"TEC-AC-10004659;Technology;Accessories;""Imatio...",NaN,NaN,NaN
1657,"TEC-MA-10001127;Technology;Machines;""HP Design...",NaN,NaN,NaN
1731,"TEC-PH-10000702;Technology;Phones;""Square Cred...",NaN,NaN,NaN
1891,"TEC-PH-10004924;Technology;Phones;""SKILCRAFT T...",NaN,NaN,NaN

In [38]:

malformed_rows= (
    Products['Category'].isna() & 
    Products['Sub-Category'].isna() &
    Products['Product Name,,,,,'].isna())


Products.loc[malformed_rows,'Product ID'].str.split(';',expand=True)

,0,1,2,3,4
26,FUR-BO-10002916,Furniture,Bookcases,"""Rush Hierlooms Collection 1"""" Thick Stackable...",None
142,FUR-FU-10000087,Furniture,Furnishings,"""Executive Impressions 14"""" Two-Color Numerals...",None
147,FUR-FU-10000222,Furniture,Furnishings,"""Seth Thomas 16"""" Steel Case Clock"",,,,,",None
149,FUR-FU-10000260,Furniture,Furnishings,"""6"""" Cubicle Wall Clock,"" Black"""""",,,,",None
152,FUR-FU-10000305,Furniture,Furnishings,"""Tenex V2T-RE Standard Weight Series Chair Mat...",None
...,...,...,...,...,...
1479,OFF-SU-10004782,Office Supplies,Supplies,"""Elite 5"""" Scissors"",,,,,",None
1615,TEC-AC-10004659,Technology,Accessories,"""ImationSecure+ Hardware Encrypted USB 2.0Fl...","16GB"",,,,,"
1657,TEC-MA-10001127,Technology,Machines,"""HP Designjet T520 Inkjet Large Format Printer...",None
1731,TEC-PH-10000702,Technology,Phones,"""Square Credit Card Reader,"" 4 1/2"""""""" x 4 1/2...",None
1891,TEC-PH-10004924,Technology,Phones,"""SKILCRAFT Telephone Shoulder Rest,"" 2"""""""" x 6...",None

In [39]:
Products.loc[malformed_rows,['Product ID', 'Category', 'Sub-Category', 'Product Name,,,,,']] = Products.loc[malformed_rows,'Product ID'].str.split(';', n=3, expand=True).values

In [40]:
Products.head()

,Product ID,Category,Sub-Category,"Product Name,,,,,"
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cher..."
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."
2,FUR-BO-10000362,Furniture,Bookcases,"Sauder Inglewood Library Bookcases,,,,,"
3,FUR-BO-10000468,Furniture,Bookcases,"O'Sullivan 2-Shelf Heavy-Duty Bookcases,,,,,"
4,FUR-BO-10000711,Furniture,Bookcases,"Hon Metal Bookcases, Gray,,,,"

In [41]:
Products['Product Name,,,,,'] = Products['Product Name,,,,,'].str.rstrip(',')
Products['Product Name'] = Products['Product Name,,,,,']

In [42]:
Products = Products.drop('Product Name,,,,,', axis=1)

In [43]:
Products.head()

,Product ID,Category,Sub-Category,Product Name
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cherry"
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."
2,FUR-BO-10000362,Furniture,Bookcases,Sauder Inglewood Library Bookcases
3,FUR-BO-10000468,Furniture,Bookcases,O'Sullivan 2-Shelf Heavy-Duty Bookcases
4,FUR-BO-10000711,Furniture,Bookcases,"Hon Metal Bookcases, Gray"

In [44]:
Products[Products['Product ID'].duplicated(keep=False)]

,Product ID,Category,Sub-Category,Product Name
18,FUR-BO-10002213,Furniture,Bookcases,DMI Eclipse Executive Suite Bookcases
19,FUR-BO-10002213,Furniture,Bookcases,"Sauder Forest Hills Library, Woodland Oak Finish"
66,FUR-CH-10001146,Furniture,Chairs,"Global Value Mid-Back Manager's Chair, Gray"
67,FUR-CH-10001146,Furniture,Chairs,"Global Task Chair, Black"
185,FUR-FU-10001473,Furniture,Furnishings,DAX Wood Document Frame
...,...,...,...,...
1789,TEC-PH-10002200,Technology,Phones,Aastra 6757i CT Wireless VoIP phone
1793,TEC-PH-10002310,Technology,Phones,Panasonic KX T7731-B Digital phone
1794,TEC-PH-10002310,Technology,Phones,Plantronics Calisto P620-M USB Wireless Speake...
1874,TEC-PH-10004531,Technology,Phones,OtterBox Commuter Series Case - iPhone 5 & 5s
1875,TEC-PH-10004531,Technology,Phones,AT&T CL2909

In [46]:
data_ord='C:/Users/DELL/Projects/ecommerce-sales-pipeline/data/Orders.csv'
Orders= pd.read_csv(data_ord, encoding = 'latin1',sep=";")
print(Orders)
Orders.info

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2022-152156  08/11/2022  11/11/2022    Second Class
1          2  CA-2022-152156  08/11/2022  11/11/2022    Second Class
2          3  CA-2022-138688  12/06/2022  16/06/2022    Second Class
3          4  US-2021-108966  11/10/2021  18/10/2021  Standard Class
4          5  US-2021-108966  11/10/2021  18/10/2021  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2020-110422  21/01/2020  23/01/2020    Second Class
9990    9991  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9991    9992  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9992    9993  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9993    9994  CA-2023-119914  04/05/2023  09/05/2023    Second Class

     Customer ID    Segment  Postal Code       Product ID     Sales  Quantity  \
0       CG-12520   Consumer        42420  FUR-BO-10001798  261.9600         2
1       CG-12520   Consumer        42420  FUR-CH-10000454  731.9400         3
2       DV-13045  Corporate        90036  OFF-LA-10000240   14.6200         2
3       SO-20335   Consumer        33311  FUR-TA-10000577  957.5775         5
4       SO-20335   Consumer        33311  OFF-ST-10000760   22.3680         2
...          ...        ...          ...              ...       ...       ...
9989    TB-21400   Consumer        33180  FUR-FU-10001889   25.2480         3
9990    DB-13060   Consumer        92627  FUR-FU-10000747   91.9600         2
9991    DB-13060   Consumer        92627  TEC-PH-10003645  258.5760         2
9992    DB-13060   Consumer        92627  OFF-PA-10004041   29.6000         4
9993    CC-12220   Consumer        92683  OFF-AP-10002684  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 13 columns]

<bound method DataFrame.info of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2022-152156  08/11/2022  11/11/2022    Second Class
1          2  CA-2022-152156  08/11/2022  11/11/2022    Second Class
2          3  CA-2022-138688  12/06/2022  16/06/2022    Second Class
3          4  US-2021-108966  11/10/2021  18/10/2021  Standard Class
4          5  US-2021-108966  11/10/2021  18/10/2021  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2020-110422  21/01/2020  23/01/2020    Second Class
9990    9991  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9991    9992  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9992    9993  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9993    9994  CA-2023-119914  04/05/2023  09/05/2023    Second Class

     Customer ID    Segment  Postal Code       Product ID     Sales  Quantity  \
0       CG-12520   Consumer        42420  FUR-BO-10001798  261.9600         2
1       CG-12520   Consumer        42420  FUR-CH-10000454  731.9400         3
2       DV-13045  Corporate        90036  OFF-LA-10000240   14.6200         2
3       SO-20335   Consumer        33311  FUR-TA-10000577  957.5775         5
4       SO-20335   Consumer        33311  OFF-ST-10000760   22.3680         2
...          ...        ...          ...              ...       ...       ...
9989    TB-21400   Consumer        33180  FUR-FU-10001889   25.2480         3
9990    DB-13060   Consumer        92627  FUR-FU-10000747   91.9600         2
9991    DB-13060   Consumer        92627  TEC-PH-10003645  258.5760         2
9992    DB-13060   Consumer        92627  OFF-PA-10004041   29.6000         4
9993    CC-12220   Consumer        92683  OFF-AP-10002684  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 13 columns]>

In [48]:
def profile_col(df):
    profile = {
        "Data types": df.dtypes,
        "Missing values":df.isna().sum(),
        "Missing percentage": (df.isna().mean() * 100 ).round(2),
        "Unique values": df.nunique(),
        "duplicate":df.duplicated().sum()
    }
    return pd.DataFrame(profile)

profile_col(Orders)

,Data types,Missing values,Missing percentage,Unique values,duplicate
Row ID,int64,0,0.0,9994,0
Order ID,object,0,0.0,5009,0
Order Date,object,0,0.0,1236,0
Ship Date,object,0,0.0,1334,0
Ship Mode,object,0,0.0,4,0
Customer ID,object,0,0.0,793,0
Segment,object,0,0.0,3,0
Postal Code,int64,0,0.0,630,0
Product ID,object,0,0.0,1862,0
Sales,float64,0,0.0,5825,0
Quantity,int64,0,0.0,14,0
Discount,float64,0,0.0,12,0
Profit,float64,0,0.0,7287,0

In [49]:
Orders['Ship Date']= pd.to_datetime(Orders['Ship Date'],format="%d/%m/%Y")
Orders['Order Date']=pd.to_datetime(Orders['Order Date'],format="%d/%m/%Y")

In [51]:
Orders['Postal Code'].astype('str')

0       42420
1       42420
2       90036
3       33311
4       33311
        ...
9989    33180
9990    92627
9991    92627
9992    92627
9993    92683
Name: Postal Code, Length: 9994, dtype: object