In [ ]:
# data profiling
import pandas as pd
data ='C:/Users/DELL/Projects/ecommerce-sales-pipeline/data/Customers.csv'
customers= pd.read_csv(data, encoding = 'latin1',sep=";")
print(customers)
customers.info
#encoding is set to latin1 because the csv is not encoded in UTF-8, hence errors when reading the csv file 
# use sep=';' so that  we can split fields. But csv are comma-delimited by default

    Customer ID       Customer Name
0      AA-10315          Alex Avila
1      AA-10375        Allen Armold
2      AA-10480        Andrew Allen
3      AA-10645       Anna Andreadi
4      AB-10015       Aaron Bergman
..          ...                 ...
788    XP-21865        Xylona Preis
789    YC-21895      Yoseph Carroll
790    YS-21880       Yana Sorensen
791    ZC-21910    Zuschuss Carroll
792    ZD-21925  Zuschuss Donatelli

[793 rows x 2 columns]

<bound method DataFrame.info of     Customer ID       Customer Name
0      AA-10315          Alex Avila
1      AA-10375        Allen Armold
2      AA-10480        Andrew Allen
3      AA-10645       Anna Andreadi
4      AB-10015       Aaron Bergman
..          ...                 ...
788    XP-21865        Xylona Preis
789    YC-21895      Yoseph Carroll
790    YS-21880       Yana Sorensen
791    ZC-21910    Zuschuss Carroll
792    ZD-21925  Zuschuss Donatelli

[793 rows x 2 columns]>

In [3]:
data_loc='C:/Users/DELL/Projects/ecommerce-sales-pipeline/data/Location.csv'
Location= pd.read_csv(data_loc, encoding = 'latin1',sep=";")
print(Location)
customers.info

     Postal Code             City       State   Region Country/Region
0        76106.0       Fort Worth       Texas  Central  United States
1        53711.0          Madison   Wisconsin  Central  United States
2        68025.0          Fremont    Nebraska  Central  United States
3        77095.0          Houston       Texas  Central  United States
4        75080.0       Richardson       Texas  Central  United States
..           ...              ...         ...      ...            ...
627      83301.0       Twin Falls       Idaho     West  United States
628      92672.0     San Clemente  California     West  United States
629      94568.0           Dublin  California     West  United States
630      93405.0  San Luis Obispo  California     West  United States
631      95240.0             Lodi  California     West  United States

[632 rows x 5 columns]

<bound method DataFrame.info of     Customer ID       Customer Name
0      AA-10315          Alex Avila
1      AA-10375        Allen Armold
2      AA-10480        Andrew Allen
3      AA-10645       Anna Andreadi
4      AB-10015       Aaron Bergman
..          ...                 ...
788    XP-21865        Xylona Preis
789    YC-21895      Yoseph Carroll
790    YS-21880       Yana Sorensen
791    ZC-21910    Zuschuss Carroll
792    ZD-21925  Zuschuss Donatelli

[793 rows x 2 columns]>

In [4]:
data_pro='C:/Users/DELL/Projects/ecommerce-sales-pipeline/data/Products.csv'
Products= pd.read_csv(data_pro, encoding = 'latin1',sep=";")
print(Products)
Products.info

                                             Product ID    Category  \
0                                       FUR-BO-10000112   Furniture
1                                       FUR-BO-10000330   Furniture
2                                       FUR-BO-10000362   Furniture
3                                       FUR-BO-10000468   Furniture
4                                       FUR-BO-10000711   Furniture
...                                                 ...         ...
1889                                    TEC-PH-10004912  Technology
1890                                    TEC-PH-10004922  Technology
1891  TEC-PH-10004924;Technology;Phones;"SKILCRAFT T...         NaN
1892                                    TEC-PH-10004959  Technology
1893                                    TEC-PH-10004977  Technology

     Sub-Category                                  Product Name,,,,,
0       Bookcases  Bush Birmingham Collection Bookcase, Dark Cher...
1       Bookcases  Sauder Camden County Barrister Bookcase, Plank...
2       Bookcases            Sauder Inglewood Library Bookcases,,,,,
3       Bookcases       O'Sullivan 2-Shelf Heavy-Duty Bookcases,,,,,
4       Bookcases                      Hon Metal Bookcases, Gray,,,,
...           ...                                                ...
1889       Phones             Cisco SPA112 2 Port Phone Adapter,,,,,
1890       Phones        RCA Visys Integrated PBX 8-Line Router,,,,,
1891          NaN                                                NaN
1892       Phones        Classic Ivory AntiqueTelephoneZL1810,,,,,
1893       Phones                                   GE 30524EE4,,,,,

[1894 rows x 4 columns]

<bound method DataFrame.info of                                              Product ID    Category  \
0                                       FUR-BO-10000112   Furniture
1                                       FUR-BO-10000330   Furniture
2                                       FUR-BO-10000362   Furniture
3                                       FUR-BO-10000468   Furniture
4                                       FUR-BO-10000711   Furniture
...                                                 ...         ...
1889                                    TEC-PH-10004912  Technology
1890                                    TEC-PH-10004922  Technology
1891  TEC-PH-10004924;Technology;Phones;"SKILCRAFT T...         NaN
1892                                    TEC-PH-10004959  Technology
1893                                    TEC-PH-10004977  Technology

     Sub-Category                                  Product Name,,,,,
0       Bookcases  Bush Birmingham Collection Bookcase, Dark Cher...
1       Bookcases  Sauder Camden County Barrister Bookcase, Plank...
2       Bookcases            Sauder Inglewood Library Bookcases,,,,,
3       Bookcases       O'Sullivan 2-Shelf Heavy-Duty Bookcases,,,,,
4       Bookcases                      Hon Metal Bookcases, Gray,,,,
...           ...                                                ...
1889       Phones             Cisco SPA112 2 Port Phone Adapter,,,,,
1890       Phones        RCA Visys Integrated PBX 8-Line Router,,,,,
1891          NaN                                                NaN
1892       Phones        Classic Ivory AntiqueTelephoneZL1810,,,,,
1893       Phones                                   GE 30524EE4,,,,,

[1894 rows x 4 columns]>

In [5]:
data_ord='C:/Users/DELL/Projects/ecommerce-sales-pipeline/data/Orders.csv'
Orders= pd.read_csv(data_ord, encoding = 'latin1',sep=";")
print(Orders)
Orders.info

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2022-152156  08/11/2022  11/11/2022    Second Class
1          2  CA-2022-152156  08/11/2022  11/11/2022    Second Class
2          3  CA-2022-138688  12/06/2022  16/06/2022    Second Class
3          4  US-2021-108966  11/10/2021  18/10/2021  Standard Class
4          5  US-2021-108966  11/10/2021  18/10/2021  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2020-110422  21/01/2020  23/01/2020    Second Class
9990    9991  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9991    9992  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9992    9993  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9993    9994  CA-2023-119914  04/05/2023  09/05/2023    Second Class

     Customer ID    Segment  Postal Code       Product ID     Sales  Quantity  \
0       CG-12520   Consumer        42420  FUR-BO-10001798  261.9600         2
1       CG-12520   Consumer        42420  FUR-CH-10000454  731.9400         3
2       DV-13045  Corporate        90036  OFF-LA-10000240   14.6200         2
3       SO-20335   Consumer        33311  FUR-TA-10000577  957.5775         5
4       SO-20335   Consumer        33311  OFF-ST-10000760   22.3680         2
...          ...        ...          ...              ...       ...       ...
9989    TB-21400   Consumer        33180  FUR-FU-10001889   25.2480         3
9990    DB-13060   Consumer        92627  FUR-FU-10000747   91.9600         2
9991    DB-13060   Consumer        92627  TEC-PH-10003645  258.5760         2
9992    DB-13060   Consumer        92627  OFF-PA-10004041   29.6000         4
9993    CC-12220   Consumer        92683  OFF-AP-10002684  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 13 columns]

<bound method DataFrame.info of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2022-152156  08/11/2022  11/11/2022    Second Class
1          2  CA-2022-152156  08/11/2022  11/11/2022    Second Class
2          3  CA-2022-138688  12/06/2022  16/06/2022    Second Class
3          4  US-2021-108966  11/10/2021  18/10/2021  Standard Class
4          5  US-2021-108966  11/10/2021  18/10/2021  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2020-110422  21/01/2020  23/01/2020    Second Class
9990    9991  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9991    9992  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9992    9993  CA-2023-121258  26/02/2023  03/03/2023  Standard Class
9993    9994  CA-2023-119914  04/05/2023  09/05/2023    Second Class

     Customer ID    Segment  Postal Code       Product ID     Sales  Quantity  \
0       CG-12520   Consumer        42420  FUR-BO-10001798  261.9600         2
1       CG-12520   Consumer        42420  FUR-CH-10000454  731.9400         3
2       DV-13045  Corporate        90036  OFF-LA-10000240   14.6200         2
3       SO-20335   Consumer        33311  FUR-TA-10000577  957.5775         5
4       SO-20335   Consumer        33311  OFF-ST-10000760   22.3680         2
...          ...        ...          ...              ...       ...       ...
9989    TB-21400   Consumer        33180  FUR-FU-10001889   25.2480         3
9990    DB-13060   Consumer        92627  FUR-FU-10000747   91.9600         2
9991    DB-13060   Consumer        92627  TEC-PH-10003645  258.5760         2
9992    DB-13060   Consumer        92627  OFF-PA-10004041   29.6000         4
9993    CC-12220   Consumer        92683  OFF-AP-10002684  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 13 columns]>

In [6]:
def profile_col(df):
    profile = {
        "Data types": df.dtypes,
        "Missing values":df.isna().sum(),
        "Missing percentage": (df.isna().mean() * 100 ).round(2),
        "Unique values": df.nunique(),
        "duplicate":df.duplicated().sum()
    }
    return pd.DataFrame(profile)

profile_col(Products)

,Data types,Missing values,Missing percentage,Unique values,duplicate
Product ID,object,0,0.00,1869,0
Category,object,148,7.81,3,0
Sub-Category,object,148,7.81,17,0
"Product Name,,,,,",object,148,7.81,1702,0

In [7]:
customers['Customer ID'].duplicated().sum()

np.int64(0)

In [8]:


def uncover_location(df2):
    return pd.DataFrame({
        "Metric": [
            "Rows with missing values",
            "Duplicate postal codes",
        ],
        "Count": [
            df2.isna().any(axis=1).sum(),
            df2.duplicated().sum(),
        ],
    })

uncover_location(Location)

                     Metric  Count
0  Rows with missing values      1
1    Duplicate postal codes      0

In [9]:
Products.isna().sum()

Product ID             0
Category             148
Sub-Category         148
Product Name,,,,,    148
dtype: int64

In [10]:
Products[Products.isna().any(axis=1)]

,Product ID,Category,Sub-Category,"Product Name,,,,,"
26,"FUR-BO-10002916;Furniture;Bookcases;""Rush Hier...",NaN,NaN,NaN
142,"FUR-FU-10000087;Furniture;Furnishings;""Executi...",NaN,NaN,NaN
147,"FUR-FU-10000222;Furniture;Furnishings;""Seth Th...",NaN,NaN,NaN
149,"FUR-FU-10000260;Furniture;Furnishings;""6"""" Cub...",NaN,NaN,NaN
152,"FUR-FU-10000305;Furniture;Furnishings;""Tenex V...",NaN,NaN,NaN
...,...,...,...,...
1479,"OFF-SU-10004782;Office Supplies;Supplies;""Elit...",NaN,NaN,NaN
1615,"TEC-AC-10004659;Technology;Accessories;""Imatio...",NaN,NaN,NaN
1657,"TEC-MA-10001127;Technology;Machines;""HP Design...",NaN,NaN,NaN
1731,"TEC-PH-10000702;Technology;Phones;""Square Cred...",NaN,NaN,NaN
1891,"TEC-PH-10004924;Technology;Phones;""SKILCRAFT T...",NaN,NaN,NaN

In [11]:
Orders.duplicated().sum()

np.int64(0)

In [12]:
Location.duplicated().sum()

np.int64(0)

In [13]:
Products['Product ID'].nunique()

1869

In [ ]:
#referential integrity check for customer id in orders 

invalid_orders= Orders[~Orders['Customer ID'].isin(customers['Customer ID'])]

print(len(invalid_orders))

0

In [ ]:
#referential integrity check for product id in orders 

invalid_products= Orders[~Orders['Product ID'].isin(Products['Product ID'])]

print(invalid_products)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
16        17  CA-2020-105893  11/11/2020  18/11/2020  Standard Class
20        21  CA-2020-143336  27/08/2020  01/09/2020    Second Class
32        33  US-2021-150630  17/09/2021  21/09/2021  Standard Class
37        38  CA-2021-117415  27/12/2021  31/12/2021  Standard Class
63        64  CA-2021-135545  24/11/2021  30/11/2021  Standard Class
...      ...             ...         ...         ...             ...
9928    9929  CA-2022-129630  04/09/2022  04/09/2022        Same Day
9956    9957  US-2020-143287  11/11/2020  17/11/2020  Standard Class
9963    9964  CA-2021-143700  26/07/2021  26/07/2021        Same Day
9985    9986  CA-2021-100251  17/05/2021  23/05/2021  Standard Class
9992    9993  CA-2023-121258  26/02/2023  03/03/2023  Standard Class

     Customer ID      Segment  Postal Code       Product ID    Sales  \
16      PK-19075     Consumer        53711  OFF-ST-10004186  665.880
20      ZD-21925     Consumer        94109  OFF-BI-10002215   22.720
32      TB-21520     Consumer        19140  OFF-BI-10001525    6.858
37      SN-20710  Home Office        77041  OFF-EN-10002986  113.328
63      KM-16720     Consumer        90004  OFF-BI-10001078   25.824
...          ...          ...          ...              ...      ...
9928    IM-15055     Consumer        94122  FUR-FU-10000260   24.270
9956    KN-16705  Home Office        10801  OFF-PA-10001776   46.350
9963    AS-10240     Consumer        19140  OFF-PA-10003072   10.368
9985    DV-13465     Consumer        11561  OFF-SU-10000898   55.600
9992    DB-13060     Consumer        92627  OFF-PA-10004041   29.600

      Quantity  Discount   Profit
16           6       0.0  13.3176
20           4       0.2   7.3840
32           6       0.7  -5.7150
37           9       0.2  35.4150
63           6       0.2   9.3612
...        ...       ...      ...
9928         3       0.0   8.7372
9956         5       0.0  21.7845
9963         2       0.2   3.6288
9985         4       0.0  16.1240
9992         4       0.0  13.3200

[771 rows x 13 columns]

In [16]:
#referential integrity check for postal code in orders 

invalid_postal= Orders[~Orders['Postal Code'].isin(Location['Postal Code'])]

print(len(invalid_postal))

0

In [17]:
is_unique = not Orders.duplicated(subset=['Order ID','Product ID']).any()
print(is_unique)

False

In [18]:
print(Products.loc[1800])

Product ID                                 TEC-PH-10002447
Category                                        Technology
Sub-Category                                        Phones
Product Name,,,,,    AT&T CL83451 4-Handset Telephone,,,,,
Name: 1800, dtype: object

In [19]:
Orders['Order Date'].max()

'31/12/2022'

In [20]:
Orders['Order Date'].min()

'01/01/2023'

In [21]:
Orders['Ship Date'].max()

'31/12/2023'

In [22]:
Orders['Ship Date'].min()

'01/01/2021'

In [23]:
(Orders['Ship Date'] < Orders['Order Date']).any()

np.True_

In [24]:
Orders[Orders.duplicated(subset=['Order ID','Product ID'], keep=False)].head(10)


#Why keep=False? By default, duplicated() hides the first instance of a repeated pair. Using keep=False ensures both the original row and its
#duplicates are included in the results so you can inspect them together.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Postal Code,Product ID,Sales,Quantity,Discount,Profit
350,351,CA-2022-129714,01/09/2022,03/09/2022,First Class,AB-10060,Home Office,10009,OFF-PA-10001970,24.560,2,0.0,11.5432
352,353,CA-2022-129714,01/09/2022,03/09/2022,First Class,AB-10060,Home Office,10009,OFF-PA-10001970,49.120,4,0.0,23.0864
430,431,US-2022-123750,15/04/2022,21/04/2022,Standard Class,RB-19795,Home Office,28052,TEC-AC-10004659,408.744,7,0.2,76.6395
431,432,US-2022-123750,15/04/2022,21/04/2022,Standard Class,RB-19795,Home Office,28052,TEC-AC-10004659,291.960,5,0.2,54.7425
1300,1301,CA-2022-137043,23/12/2022,25/12/2022,Second Class,LC-17140,Consumer,22153,FUR-FU-10003664,572.760,6,0.0,166.1004
1301,1302,CA-2022-137043,23/12/2022,25/12/2022,Second Class,LC-17140,Consumer,22153,FUR-FU-10003664,286.380,3,0.0,83.0502
3183,3184,CA-2023-152912,09/11/2023,12/11/2023,Second Class,BM-11650,Corporate,21044,OFF-ST-10003208,1633.140,9,0.0,473.6106
3184,3185,CA-2023-152912,09/11/2023,12/11/2023,Second Class,BM-11650,Corporate,21044,OFF-ST-10003208,544.380,3,0.0,157.8702
3405,3406,US-2020-150119,23/04/2020,27/04/2020,Standard Class,LB-16795,Home Office,43229,FUR-CH-10002965,281.372,2,0.3,-12.0588
3406,3407,US-2020-150119,23/04/2020,27/04/2020,Standard Class,LB-16795,Home Office,43229,FUR-CH-10002965,281.372,2,0.3,-12.0588

In [25]:
pro_len=Products[Products.duplicated(subset=['Product ID'])].head(25)
print(pro_len)

           Product ID         Category Sub-Category  \
19    FUR-BO-10002213        Furniture    Bookcases
67    FUR-CH-10001146        Furniture       Chairs
186   FUR-FU-10001473        Furniture  Furnishings
396   OFF-AP-10000576  Office Supplies   Appliances
516   OFF-AR-10001149  Office Supplies          Art
732   OFF-BI-10002026  Office Supplies      Binders
843   OFF-BI-10004632  Office Supplies      Binders
845   OFF-BI-10004654  Office Supplies      Binders
1058  OFF-PA-10000357  Office Supplies        Paper
1064  OFF-PA-10000477  Office Supplies        Paper
1080  OFF-PA-10000659  Office Supplies        Paper
1103  OFF-PA-10001166  Office Supplies        Paper
1162  OFF-PA-10001970  Office Supplies        Paper
1219  OFF-PA-10003022  Office Supplies        Paper
1353  OFF-ST-10001228  Office Supplies      Storage
1441  OFF-ST-10004950  Office Supplies      Storage
1541  TEC-AC-10002049       Technology  Accessories
1558  TEC-AC-10002550       Technology  Accessories
1595  TEC-AC-10003832       Technology  Accessories
1659  TEC-MA-10001148       Technology     Machines
1756  TEC-PH-10001530       Technology       Phones
1769  TEC-PH-10001795       Technology       Phones
1789  TEC-PH-10002200       Technology       Phones
1794  TEC-PH-10002310       Technology       Phones
1875  TEC-PH-10004531       Technology       Phones

                                      Product Name,,,,,
19    Sauder Forest Hills Library, Woodland Oak Fini...
67                         Global Task Chair, Black,,,,
186   Eldon Executive Woodline II Desk Accessories, ...
396            Belkin 325VA UPS Surge Protector, 6',,,,
516   Avery Hi-Liter Comfort Grip Fluorescent Highli...
732              Ibico Recycled Linen-Style Covers,,,,,
843                             GBC Binding covers,,,,,
845                     VariCap6 Expandable Binder,,,,,
1058                                    Xerox 1888,,,,,
1064                                      Xerox 22,,,,,
1080  TOPS Carbonless Receipt Book, Four 2-3/4 x 7-1...
1103                                    Xerox 1932,,,,,
1162                                    Xerox 1908,,,,,
1219  Standard Line ?While You Were Out? Hardbound T...
1353  Personal File Boxes with Fold-Down Carry Handl...
1441  Tenex Personal Filing Tote With Secure Closure...
1541  Plantronics Savi W720 Multi-Device Wireless He...
1558  Memorex 25GB 6X Branded Blu-Ray Recordable Dis...
1595  Imation16GB Mini TravelDrive USB 2.0Flash Dr...
1659           Okidata MB491 Multifunction Printer,,,,,
1756                Plantronics Voyager Pro Legend,,,,,
1769  RCA H5401RE1 DECT 6.0 4-Line Cordless Handset ...
1789           Aastra 6757i CT Wireless VoIP phone,,,,,
1794  Plantronics Calisto P620-M USB Wireless Speake...
1875                                   AT&T CL2909,,,,,

In [ ]:
Products[Products['Product ID']=='FUR-BO-10002213']
# row with duplicate product i but different product name

,Product ID,Category,Sub-Category,"Product Name,,,,,"
18,FUR-BO-10002213,Furniture,Bookcases,"DMI Eclipse Executive Suite Bookcases,,,,,"
19,FUR-BO-10002213,Furniture,Bookcases,"Sauder Forest Hills Library, Woodland Oak Fini..."

In [27]:
Products.head(5)

,Product ID,Category,Sub-Category,"Product Name,,,,,"
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cher..."
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."
2,FUR-BO-10000362,Furniture,Bookcases,"Sauder Inglewood Library Bookcases,,,,,"
3,FUR-BO-10000468,Furniture,Bookcases,"O'Sullivan 2-Shelf Heavy-Duty Bookcases,,,,,"
4,FUR-BO-10000711,Furniture,Bookcases,"Hon Metal Bookcases, Gray,,,,"

In [28]:
Products.tail(1)

           Product ID    Category Sub-Category Product Name,,,,,
1893  TEC-PH-10004977  Technology       Phones  GE 30524EE4,,,,,

In [29]:
Orders['Ship Date']= pd.to_datetime(Orders['Ship Date'],format="%d/%m/%Y")

In [30]:
Orders['Order Date']= pd.to_datetime(Orders['Order Date'],format="%d/%m/%Y")

In [31]:
Orders.dtypes

Row ID                  int64
Order ID               object
Order Date     datetime64[ns]
Ship Date      datetime64[ns]
Ship Mode              object
Customer ID            object
Segment                object
Postal Code             int64
Product ID             object
Sales                 float64
Quantity                int64
Discount              float64
Profit                float64
dtype: object

In [32]:
earliest = Orders['Ship Date'].min()
latest = Orders['Ship Date'].max()
print(f"Earliest date:",{earliest})
print(f"Latest date:",{latest})

Earliest date: {Timestamp('2020-01-07 00:00:00')}
Latest date: {Timestamp('2024-01-05 00:00:00')}

In [33]:
earliest = Orders['Ship Date'].min()
latest = Orders['Ship Date'].max()
print(f"Earliest date:",{earliest})
print(f"Latest date:",{latest})

Earliest date: {Timestamp('2020-01-07 00:00:00')}
Latest date: {Timestamp('2024-01-05 00:00:00')}

In [ ]:
(Orders['Ship Date'] < Orders['Order Date']).any()

# no ship date was before an order date

np.False_

In [35]:
Orders[Orders.duplicated( keep=False)].head(10)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Segment, Postal Code, Product ID, Sales, Quantity, Discount, Profit]
Index: []